"use client";

import SidebarLayout from "@/app/components/sidebarLayout";
import {
  AlertDialog,
  AlertDialogBody,
  AlertDialogContent,
  AlertDialogOverlay,
  Box,
  Button,
  Divider,
  Flex,
  Grid,
  GridItem,
  InputGroup,
  InputRightElement,
  NumberInput,
  NumberInputField,
  Text,
  Image,
} from "@chakra-ui/react";
import styles from "../../styles/remuneration.module.css";
import useRemuneration from "./useRemuneration";

const Remuneration = () => {
  const { data, handleInputChange, onSubmit, isOpen, onClose, cancelRef } = useRemuneration();

  return (
    <>
      <SidebarLayout>
        <Box className={styles["remuneration-container"]}>
          <Text className={styles["remuneration-title"]} mb={"1rem"}>
            Setup - Remuneration
          </Text>
          <Text className={styles["remuneration-subtitle"]} mb={"1rem"}>
            Skema Normal & Khusus
          </Text>
          <Grid templateColumns="1fr auto 1fr;" gap="70px" mb={"2rem"}>
            <GridItem>
              <Text className={styles["remuneration-subtitle"]}>
                Remunerasi Per Bulan
              </Text>
            </GridItem>
            <GridItem>
              <span></span>
            </GridItem>
            <GridItem>
              <Text className={styles["remuneration-subtitle"]}>
                Remunerasi Sisa kontrak
              </Text>
            </GridItem>
          </Grid>
          <Grid templateColumns="1fr auto 1fr;" gap="70px">
            <GridItem>
              <Flex
                direction={"column"}
                gap={"12px"}
                wrap="nowrap"
                mb={"2rem"}
              >
                <Text
                  className={styles["remuneration-form-title"]}
                  mb={"1rem"}
                >
                  Penambah Gaji
                </Text>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      Basic Salary:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="bulan.basic_salary"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.bulan?.basic_salary}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      Tunjangan Posisi:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="bulan.position_allowance"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.bulan?.position_allowance}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      BPJSTK Iuran JKK:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="bulan.bpjstk_jkk_company"
                        min={0}
                        max={100}
                        value={data?.bulan?.bpjstk_jkk_company}
                        step="any"
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      BPJSTK Iuran JKM:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="bulan.bpjstk_jkm_company"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.bulan?.bpjstk_jkm_company}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      BPJSTK Iuran JHT:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="bulan.bpjstk_jht_company"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.bulan?.bpjstk_jht_employee}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      BPJSTK Iuran JP:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="bulan.bpjstk_jp_company"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.bulan?.premi_bpjskes_employee}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      Premi BPJSKES:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="bulan.premi_bpjskes_company"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.bulan?.premi_bpjskes_employee}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      Pajak:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="bulan.tax_company"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.bulan?.tax_company}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
              </Flex>
              <Flex
                direction={"column"}
                gap={"12px"}
                wrap="nowrap"
                mb={"1rem"}
              >
                <Text
                  className={styles["remuneration-form-title-2"]}
                  mb={"1rem"}
                >
                  Pengurang Gaji
                </Text>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      BPJSTK Iuran JHT:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="bulan.bpjstk_jht_employee"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.bulan?.bpjstk_jht_company}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      BPJSTK Iuran JP:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="bulan.bpjstk_jp_employee"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.bulan?.bpjstk_jp_company}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      Premi BPJSKES:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="bulan.premi_bpjskes_employee"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.bulan?.premi_bpjskes_company}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
              </Flex>
            </GridItem>
            <GridItem>
              <Divider
                size="lg"
                borderWidth="2px"
                borderColor="#AE445A"
                opacity="1"
                orientation="vertical"
              />
            </GridItem>
            <GridItem>
              <Flex
                direction={"column"}
                gap={"12px"}
                wrap="nowrap"
                mb={"2rem"}
              >
                <Text
                  className={styles["remuneration-form-title"]}
                  mb={"1rem"}
                >
                  Penambah Gaji
                </Text>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      Basic Salary:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="kontrak.basic_salary"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.kontrak?.basic_salary}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      Tunjangan Posisi:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="kontrak.position_allowance"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.kontrak?.position_allowance}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      BPJSTK Iuran JKK:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="kontrak.bpjstk_jkk_company"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.kontrak?.bpjstk_jkk_company}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      BPJSTK Iuran JKM:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="kontrak.bpjstk_jkm_company"
                        min={0}
                        max={100}
                        step="any"
                        onChangeCapture={handleInputChange}
                        value={data?.kontrak?.bpjstk_jkm_company}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      BPJSTK Iuran JHT:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="kontrak.bpjstk_jht_company"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.kontrak?.bpjstk_jht_company}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      BPJSTK Iuran JP:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="kontrak.bpjstk_jp_company"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.kontrak?.bpjstk_jp_company}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      Premi BPJSKES:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="kontrak.premi_bpjskes_company"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.kontrak?.premi_bpjskes_company}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      Pajak:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="kontrak.tax_company"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.kontrak?.tax_company}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
              </Flex>
              <Flex
                direction={"column"}
                gap={"12px"}
                wrap="nowrap"
                mb={"1rem"}
              >
                <Text
                  className={styles["remuneration-form-title-2"]}
                  mb={"1rem"}
                >
                  Pengurang Gaji
                </Text>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      BPJSTK Iuran JHT:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="kontrak.bpjstk_jht_employee"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.kontrak?.bpjstk_jht_employee}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      BPJSTK Iuran JP:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="kontrak.bpjstk_jp_employee"
                        min={0}
                        max={100}
                        value={data?.kontrak?.bpjstk_jp_employee}
                        step="any"
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
                <Box>
                  <Flex
                    align={"center"}
                    justify={"space-between"}
                    wrap="nowrap"
                  >
                    <Text className={styles["remuneration-search-text"]}>
                      Premi BPJSKES:
                    </Text>
                    <InputGroup
                      className={styles["remuneration-input-container"]}
                    >
                      <NumberInput
                        name="kontrak.premi_bpjskes_employee"
                        min={0}
                        max={100}
                        step="any"
                        value={data?.kontrak?.premi_bpjskes_employee}
                        onChangeCapture={handleInputChange}
                      >
                        <NumberInputField
                          className={styles["remuneration-input"]}
                          placeholder="0"
                        />
                      </NumberInput>
                      <InputRightElement
                        className={styles["remuneration-input-suffix"]}
                      >
                        %
                      </InputRightElement>
                    </InputGroup>
                  </Flex>
                </Box>
              </Flex>
            </GridItem>
          </Grid>
          <Flex width={"100%"} justify={"end"} marginTop={"2rem"}>
            <Button type="button" className={styles["remuneration-btn"]} onClick={onSubmit}>
              Save
            </Button>
          </Flex>
        </Box>
        <AlertDialog
          isOpen={isOpen}
          leastDestructiveRef={cancelRef}
          onClose={onClose}
        >
          <AlertDialogOverlay>
            <AlertDialogContent>
              <AlertDialogBody className={styles["remuneration-success"]}>
                <Flex
                  direction={"column"}
                  align={"center"}
                  justify={"center"}
                  gap={"24px"}
                >
                  <Image src="/images/Success-Circle.png" />
                  <Text>Data berhasil disimpan</Text>
                </Flex>
              </AlertDialogBody>
            </AlertDialogContent>
          </AlertDialogOverlay>
        </AlertDialog>
      </SidebarLayout>
    </>
  );
};

export default Remuneration;
